parameters:
    kafka_default_brokers: ['kafka:9092']
sts_gaming_group_kafka:
    producers:
        instances:
            App\Infrastructure\Checkout\Producer\CheckoutProducer:
                brokers: '%kafka_default_brokers%'
                producer_topic: 'ended-sales-topic'