parameters:
    kafka_default_brokers: ['kafka:9092']
sts_gaming_group_kafka:
    consumers:
        instances:
            App\Infrastructure\Sales\Consumer\SalesConsumer:
                brokers: '%kafka_default_brokers%'
                topics: ['sales-topic']
                decoder: StsGamingGroup\KafkaBundle\Decoder\PlainDecoder
    producers:
        instances:
            App\Infrastructure\Sales\Producer\SalesProducer:
                brokers: '%kafka_default_brokers%'
                producer_topic: 'ended-sales-topic'